function distToPath(px,py){let min=Infinity;for(let i=0;i<PATH_POINTS.length-1;i++){const a=PATH_POINTS[i],b=PATH_POINTS[i+1],dx=b.x-a.x,dy=b.y-a.y,l2=dx*dx+dy*dy;let t=l2?((px-a.x)*dx+(py-a.y)*dy)/l2:0;t=Math.max(0,Math.min(1,t));min=Math.min(min,Math.hypot(px-(a.x+t*dx),py-(a.y+t*dy)))}return min}
function createEnemyVisual(scene,x,y,r,key,color){const c=scene.add.container(x,y).setDepth(y+15);c.add(scene.add.ellipse(0,r*.9,r*1.7,r*.55,0x000000,.3));let body;
 if(key==='ogre'||key==='boss'){body=scene.add.circle(0,2,r,color).setStrokeStyle(2,0x27140f,.8);c.add(body);c.add(scene.add.rectangle(-r*.65,0,r*.38,r*.7,0x4c4a45).setRotation(-.2));c.add(scene.add.rectangle(r*.65,0,r*.38,r*.7,0x4c4a45).setRotation(.2));c.add(scene.add.circle(0,-r*.55,r*.55,0xcaa97c).setStrokeStyle(1,0x3a2117));c.add(scene.add.triangle(0,-r*.95,-r*.25,0,r*.25,0,0,-r*.4,0xcaa97c));}
 else{body=scene.add.circle(0,3,r,color).setStrokeStyle(2,0x1d2a18,.8);c.add(body);c.add(scene.add.circle(0,-r*.58,r*.48,0x9a7656).setStrokeStyle(1,0x3b2418));c.add(scene.add.triangle(-r*.35,-r*.72,-5,5,0,0,-2,-8,0x9a7656));c.add(scene.add.triangle(r*.35,-r*.72,5,5,0,0,2,-8,0x9a7656));}
 if(key==='raider'){c.add(scene.add.triangle(0,r*.1,-r, r*1.2,r,r*1.2,0,-r*.2,0xb68a35,.75));c.add(scene.add.rectangle(0,-r*.95,r*.9,4,0x38261a).setRotation(-.1))}
 if(key==='boss'){c.add(scene.add.triangle(0,-r*1.3,-r*.5,5,r*.5,5,0,-r*.35,0xe7bd5b).setStrokeStyle(1,0x8d6329));c.add(scene.add.circle(0,-r*1.22,3,0xc94a4a))}
 c.add(scene.add.circle(-r*.18,-r*.62,1.8,0x24140f));c.add(scene.add.circle(r*.18,-r*.62,1.8,0x24140f));return c}
function spawnDeathBurst(scene,x,y,color){for(let i=0;i<10;i++){const a=Math.random()*Math.PI*2,p=scene.add.circle(x,y,Phaser.Math.Between(2,4),color,.85).setDepth(40);scene.tweens.add({targets:p,x:x+Math.cos(a)*Phaser.Math.Between(15,28),y:y+Math.sin(a)*Phaser.Math.Between(15,28),alpha:0,scale:.25,duration:360,onComplete:()=>p.destroy()})}}
function makeEnemy(key,x,y,wpIndex,hp,speed,radius,reward){const s=GameState.scene,type=ENEMY_TYPES[key],sprite=createEnemyVisual(s,x,y,radius,key,type.color),barBg=s.add.rectangle(x,y-radius-9,radius*2+5,6,0x1b120e,.8).setOrigin(.5),bar=s.add.rectangle(x,y-radius-9,radius*2,3,0x7fbd59).setOrigin(.5);const e={sprite,bar,barBg,hp,maxHp:hp,speed,baseSpeed:speed,wpIndex,x,y,radius,slowUntil:0,color:type.color,reward,isBoss:key==='boss',bobSeed:Math.random()*6.28};GameState.enemies.push(e);return e}
function spawnEnemy(fast,tank){const hp=tank?90+GameState.wave*14:30+GameState.wave*8,speed=fast?90:45,r=tank?16:11,key=tank?'ogre':fast?'raider':'goblin',reward=tank?12:fast?6:5;const p=PATH_POINTS[0];return makeEnemy(key,p.x,p.y,0,hp,speed,r,reward)}
function spawnBoss(){const w=GameState.wave,p=PATH_POINTS[0],b=makeEnemy('boss',p.x,p.y,0,320+w*45,28,24,40+w*5);b.summonedReinforcements=false;return b}
function spawnMinionAt(x,y,wp){makeEnemy('goblin',x,y,wp,20+GameState.wave*5,45,11,5)}
function damageEnemy(e,dmg){if(e.dead)return;e.hp-=dmg;const s=GameState.scene;const hit=s.add.circle(e.x,e.y,Math.max(5,e.radius*.55),0xffffff,.45).setDepth(50);s.tweens.add({targets:hit,alpha:0,scale:1.7,duration:100,onComplete:()=>hit.destroy()});if(e.isBoss&&!e.summonedReinforcements&&e.hp>0&&e.hp<=e.maxHp*.5){e.summonedReinforcements=true;spawnMinionAt(e.x-22,e.y,e.wpIndex);spawnMinionAt(e.x+22,e.y,e.wpIndex);s.cameras.main.shake(180,.008)}if(e.hp<=0){e.dead=true;GameState.gold+=e.reward;updateHUD();spawnDeathBurst(s,e.x,e.y,e.color);if(e.isBoss)s.cameras.main.shake(220,.012);e.sprite.destroy();e.bar.destroy();e.barBg.destroy()}}
function killEnemyOffPath(e){e.dead=true;e.sprite.destroy();e.bar.destroy();e.barBg.destroy()}
function updateEnemies(time,delta){for(const e of GameState.enemies){if(e.dead)continue;const spd=(e.slowUntil>time?e.baseSpeed*SLOW_FACTOR:e.baseSpeed)*delta/1000,wp=PATH_POINTS[e.wpIndex+1];if(!wp){GameState.lives--;updateHUD();GameState.scene.cameras.main.shake(100,.004);killEnemyOffPath(e);if(GameState.lives<=0)showGameOver(false);continue}const dx=wp.x-e.x,dy=wp.y-e.y,d=Math.hypot(dx,dy);if(d<4)e.wpIndex++;else{e.x+=dx/d*spd;e.y+=dy/d*spd}const bob=Math.sin(time/145+e.bobSeed)*1.5;e.sprite.setPosition(e.x,e.y+bob);e.bar.setPosition(e.x,e.y-e.radius-9+bob*.4);e.barBg.setPosition(e.x,e.y-e.radius-9+bob*.4);const ratio=Math.max(0,e.hp/e.maxHp);e.bar.width=ratio*(e.radius*2);e.bar.setFillStyle(ratio<.3?0xd84d50:ratio<.6?0xe1b64e:0x7fbd59)}GameState.enemies=GameState.enemies.filter(e=>!e.dead)}
function startWave(){if(GameState.waveActive)return;GameState.wave++;GameState.waveActive=true;GameState.spawning=true;const boss=GameState.wave%BOSS_WAVE_INTERVAL===0;toggleBossTag(boss);showWaveBanner(boss?`♛ OLEADA ${GameState.wave} · REY OGRO`:`⚔ OLEADA ${GameState.wave}`);updateHUD();const count=4+GameState.wave*2;let spawned=0;GameState.scene.time.addEvent({delay:500,repeat:count-1,callback:()=>{spawned++;spawnEnemy(GameState.wave>1&&Math.random()<.3,GameState.wave>2&&Math.random()<.25);if(spawned>=count){if(boss)GameState.scene.time.delayedCall(900,()=>{spawnBoss();GameState.spawning=false});else GameState.spawning=false}}})}
function checkWaveComplete(){if(GameState.waveActive&&!GameState.spawning&&GameState.enemies.length===0){GameState.waveActive=false;GameState.gold+=25+GameState.wave*3;toggleBossTag(false);updateHUD();showRewardToast(`+${25+GameState.wave*3} oro · Oleada superada`)}}
function showRewardToast(text){const s=GameState.scene,t=s.add.text(400,105,text,{fontFamily:'Cinzel,serif',fontSize:'11px',color:'#f0d994',backgroundColor:'#1b120ddd',padding:{left:10,right:10,top:6,bottom:6}}).setOrigin(.5).setDepth(30).setAlpha(0);s.tweens.add({targets:t,alpha:1,y:92,duration:220,onComplete:()=>s.tweens.add({targets:t,alpha:0,y:80,delay:700,duration:300,onComplete:()=>t.destroy()})})}
