function createTowerVisual(scene,x,y,type,color){
  const c=scene.add.container(x,y).setDepth(y+20);c.add(scene.add.ellipse(0,16,38,13,0x000000,.25));
  const ring=scene.add.circle(0,4,18,0x40382f).setStrokeStyle(2,0x1e1b18);c.add(ring);
  if(type==='basic'){
    c.add(scene.add.rectangle(0,0,24,27,0x73583b).setStrokeStyle(2,0x332416));c.add(scene.add.triangle(0,-22,-16,9,16,9,0,-13,0x823a32).setStrokeStyle(2,0x332416));c.add(scene.add.rectangle(0,-1,12,9,0x30251c));c.add(scene.add.line(0,0,0,0,0,0));
    const archer=scene.add.text(0,-4,'⌁',{fontFamily:'serif',fontSize:22,color:'#e6c47b'}).setOrigin(.5);c.add(archer);
  }else if(type==='slow'){
    c.add(scene.add.polygon(0,-5,[-16,14,0,-29,16,14],0x44395f).setStrokeStyle(2,0x21192d));const orb=scene.add.circle(0,-25,7,color).setStrokeStyle(2,0xc4eaff,.7);c.add(orb);scene.tweens.add({targets:orb,scale:1.25,alpha:.45,duration:750,yoyo:true,repeat:-1});c.add(scene.add.text(0,1,'✦',{fontFamily:'serif',fontSize:17,color:'#c6e8ff'}).setOrigin(.5));
  }else{
    c.add(scene.add.circle(-12,9,8,0x2a2119).setStrokeStyle(2,0x120e0b));c.add(scene.add.circle(12,9,8,0x2a2119).setStrokeStyle(2,0x120e0b));c.add(scene.add.rectangle(0,3,29,10,0x654322).setStrokeStyle(2,0x2e1b10));c.add(scene.add.rectangle(5,-8,5,29,0x9a6a32).setOrigin(.5,1).setRotation(-.42));c.add(scene.add.circle(11,-17,6,0x80623d));
  }
  return c;
}
function updateLevelPips(tower){if(tower.pips)tower.pips.destroy();const s=GameState.scene,g=s.add.graphics().setDepth(tower.y+40);const sx=tower.x-(tower.level-1)*5;for(let i=0;i<tower.level;i++){g.fillStyle(0xe7bd5b,1);g.fillCircle(sx+i*10,tower.y-39,3);g.lineStyle(1,0x5d411f,1);g.strokeCircle(sx+i*10,tower.y-39,3)}tower.pips=g}
function getEffectiveStats(tower){return {...TOWER_DEFS[tower.type],...getTowerStats(tower.type,tower.level)}}
function findTowerAt(x,y){for(const t of GameState.towers)if(Math.hypot(t.x-x,t.y-y)<26)return t;return null}
function isValidPlacement(x,y,type){const def=TOWER_DEFS[type];if(GameState.gold<def.cost||y>GAME_HEIGHT-12)return false;if(distToPath(x,y)<MIN_TOWER_DISTANCE_TO_PATH)return false;for(const t of GameState.towers)if(Math.hypot(t.x-x,t.y-y)<MIN_TOWER_DISTANCE_TO_TOWER)return false;return true}
function drawPlacementPreview(x,y){const s=GameState.scene;if(!s?.previewGraphics)return;const g=s.previewGraphics;g.clear();if(!GameState.selectedTower||y>GAME_HEIGHT)return;const d=TOWER_DEFS[GameState.selectedTower],valid=isValidPlacement(x,y,GameState.selectedTower),col=valid?0x8fb56b:0xd34d46;g.fillStyle(col,.08);g.fillCircle(x,y,d.range);g.lineStyle(2,col,.65);g.strokeCircle(x,y,d.range);g.lineStyle(1,0xffffff,.2);g.strokeCircle(x,y,d.range-5);g.fillStyle(col,.85);g.fillCircle(x,y,5)}
function clearPlacementPreview(){GameState.scene?.previewGraphics?.clear()}
function selectPlacedTower(tower){GameState.selectedTower=null;document.querySelectorAll('#buildButtons .tower-btn').forEach(b=>b.classList.remove('selected'));GameState.selectedPlacedTower=tower;showTowerPanel(tower);highlightTower(tower,true)}
function deselectPlacedTower(){if(GameState.selectedPlacedTower)highlightTower(GameState.selectedPlacedTower,false);GameState.selectedPlacedTower=null;hideTowerPanel()}
function highlightTower(t,on){if(!t)return;t.visual.setScale(on?1.08:1);if(t.range)t.range.setVisible(on)}
function upgradeTower(t){if(t.level>=MAX_TOWER_LEVEL)return;const cost=getUpgradeCost(t.type,t.level);if(GameState.gold<cost)return;GameState.gold-=cost;t.invested+=cost;t.level++;updateHUD();updateLevelPips(t);refreshTowerPanel(t);const s=GameState.scene;const ring=s.add.circle(t.x,t.y,18,0xe7bd5b,.22).setDepth(t.y+50);s.tweens.add({targets:ring,scale:2.4,alpha:0,duration:400,onComplete:()=>ring.destroy()});}
function sellTower(t){const refund=Math.round(t.invested*SELL_REFUND_RATIO);GameState.gold+=refund;updateHUD();t.visual.destroy();t.range.destroy();t.pips?.destroy();GameState.towers=GameState.towers.filter(x=>x!==t);deselectPlacedTower()}
function placeTower(x,y){if(!GameState.selectedTower||!isValidPlacement(x,y,GameState.selectedTower))return;const type=GameState.selectedTower,d=TOWER_DEFS[type],s=GameState.scene;GameState.gold-=d.cost;updateHUD();const visual=createTowerVisual(s,x,y,type,d.color);const range=s.add.circle(x,y,d.range,0xffffff,0).setStrokeStyle(2,d.color,.28).setDepth(y+10).setVisible(false);const tower={x,y,type,lastShot:0,visual,range,level:1,invested:d.cost};GameState.towers.push(tower);updateLevelPips(tower);}
function shootAt(tower,enemy){const s=GameState.scene,d=getEffectiveStats(tower),tx=enemy.x,ty=enemy.y,dist=Math.hypot(tx-tower.x,ty-tower.y),duration=Math.max(100,dist/(d.area?260:520)*1000);let proj;if(d.area){proj=s.add.circle(tower.x,tower.y,7,d.proj).setStrokeStyle(2,0xffd99a,.5)}else{const a=Math.atan2(ty-tower.y,tx-tower.x);proj=s.add.rectangle(tower.x,tower.y,17,3,d.proj).setRotation(a)}s.tweens.add({targets:proj,x:tx,y:ty,duration,ease:'Linear',onComplete:()=>{proj.destroy();if(d.area){GameState.enemies.forEach(e=>{if(!e.dead&&Math.hypot(e.x-tx,e.y-ty)<AREA_BLAST_RADIUS)damageEnemy(e,d.dmg)});impactBurst(s,tx,ty,d.proj,true)}else{if(!enemy.dead){damageEnemy(enemy,d.dmg);if(d.slow&&!enemy.isBoss)enemy.slowUntil=s.time.now+SLOW_DURATION_MS}impactBurst(s,tx,ty,d.proj,false)}}});}
function impactBurst(s,x,y,color,big){const r=s.add.circle(x,y,big?7:5,color,.45).setDepth(25);s.tweens.add({targets:r,scale:big?3.5:2.2,alpha:0,duration:220,onComplete:()=>r.destroy()});for(let i=0;i<(big?10:5);i++){const a=Math.random()*Math.PI*2,p=s.add.circle(x,y,big?2.5:2,color,.8).setDepth(25);s.tweens.add({targets:p,x:x+Math.cos(a)*(big?28:14),y:y+Math.sin(a)*(big?28:14),alpha:0,duration:260,onComplete:()=>p.destroy()})}if(big)s.cameras.main.shake(90,.004)}
function updateTowers(time){for(const t of GameState.towers){const st=getEffectiveStats(t);if(time-t.lastShot<st.rate)continue;let target=null,best=Infinity;for(const e of GameState.enemies){if(e.dead)continue;const d=Math.hypot(e.x-t.x,e.y-t.y);if(d<=st.range&&d<best){best=d;target=e}}if(target){t.lastShot=time;shootAt(t,target)}}}
