const CACHE = "defensa-castillo-v8.20-sonidos";
const CORE = ["./", "./index.html", "./css/styles.css", "./js/config.js", "./js/state.js", "./js/settings.js", "./js/audio.js", "./js/music.js", "./js/ui.js", "./js/engine3d.js", "./js/nature18.js", "./js/v6.js", "./js/v65.js", "./js/v69.js", "./js/fx.js", "./js/bosses.js", "./js/skills.js", "./js/progress.js", "./js/ambience.js", "./js/visual8.js", "./js/save.js", "./js/main.js", "./js/vendor/three.min.js", "./js/vendor/GLTFLoader.js", "./manifest.webmanifest", "./assets/models/archer.glb", "./assets/models/wizard.glb", "./assets/models/catapult.glb", "./assets/models/goblin.glb", "./assets/models/raider.glb", "./assets/models/ogre.glb", "./assets/models/castle.glb", "./assets/models/enemy_soldier.glb", "./assets/models/orc.glb", "./icon.svg", "./assets/map-kit/Prop_Wagon.gltf", "./assets/map-kit/Prop_Crate.gltf", "./assets/map-kit/Prop_WoodenFence_Single.gltf", "./assets/map-kit/Prop_WoodenFence_Extension1.gltf", "./assets/map-kit/Prop_Vine1.gltf", "./assets/map-kit/Wall_Plaster_Straight.gltf", "./assets/map-kit/Wall_Plaster_Door_Round.gltf", "./assets/map-kit/Roof_RoundTiles_6x6.gltf", "./assets/map-kit/Roof_RoundTiles_6x6.bin", "./assets/map-kit/T_Plaster_Normal.png", "./assets/map-kit/T_Plaster_BaseColor.png", "./assets/map-kit/Prop_Vine1.bin", "./assets/map-kit/T_WoodTrim_BaseColor.png", "./assets/map-kit/T_RockTrim_BaseColor.png", "./assets/map-kit/T_Plaster_ORM.png", "./assets/map-kit/Wall_Plaster_Straight.bin", "./assets/map-kit/T_RockTrim_ORM.png", "./assets/map-kit/T_RockTrim_Normal.png", "./assets/map-kit/Prop_WoodenFence_Extension1.bin", "./assets/map-kit/Prop_Crate.bin", "./assets/map-kit/T_RoundTiles_Roughness.png", "./assets/map-kit/T_RoundTiles_Normal.png", "./assets/map-kit/Prop_WoodenFence_Single.bin", "./assets/map-kit/T_VineLeaf_png.png", "./assets/map-kit/Prop_Wagon.bin", "./assets/map-kit/Wall_Plaster_Door_Round.bin", "./assets/map-kit/T_RoundTiles_BaseColor.png", "./assets/map-kit/T_WoodTrim_Normal.png", "./assets/map-kit/T_WoodTrim_Roughness.png"];
self.addEventListener("install", event => event.waitUntil(caches.open(CACHE).then(c => c.addAll(CORE)).then(() => self.skipWaiting())));
self.addEventListener("activate", event => event.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k)))).then(() => self.clients.claim())));
self.addEventListener("fetch", event => {
  const req = event.request;
  if (req.method !== "GET" || new URL(req.url).origin !== location.origin) return; // tipografías y otros orígenes: que los gestione el navegador
  event.respondWith(caches.match(req).then(cached => cached || fetch(req).then(res => {
    // Solo se guardan respuestas correctas (antes un 404/500 quedaba en caché para siempre).
    if (res && res.status === 200 && res.type === "basic") { const copy = res.clone(); caches.open(CACHE).then(c => c.put(req, copy)).catch(() => {}); }
    return res;
  }).catch(() => req.mode === "navigate" ? caches.match("./index.html") : Response.error()))); // index.html solo como respaldo de páginas, no de scripts o modelos
});
